// AUTHENTICATION TYPES
export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_SUCCES = "LOGIN_SUCCES"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const REGISTER_SUCCES = "REGISTER_SUCCES"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"


// ERROR TYPES
export const GET_ERROR = "GET_ERROR"
export const CLEAR_ERROR = "CLEAR_ERROR"